models:
- context_window: 8192
  cost_per_1k_input: 0.03
  cost_per_1k_output: 0.06
  max_tokens: 4096
  model_id: gpt-4
  name: gpt-4
  provider: openai
  supports_functions: true
  supports_vision: false
  temperature: 0.7
- context_window: 16384
  cost_per_1k_input: 0.001
  cost_per_1k_output: 0.002
  max_tokens: 4096
  model_id: gpt-3.5-turbo
  name: gpt-3.5-turbo
  provider: openai
  supports_functions: true
  supports_vision: false
  temperature: 0.7
- context_window: 200000
  cost_per_1k_input: 0.00025
  cost_per_1k_output: 0.00125
  max_tokens: 4096
  model_id: claude-3-haiku-20240307
  name: claude-3-haiku
  provider: anthropic
  supports_functions: false
  supports_vision: true
  temperature: 0.7
